Feature/27 time api
shal/mono pull request #28
Opened 2020-07-10 20:57 UTC by SuddenGunter

fix for #27

2020-07-12 09:31 UTC, shal requested changes

2020-07-12 09:31 UTC, shal commented on time_test.go
> +func TestTime_JsonUnmarshal(t *testing.T) {
Usually, we call tests with the following name convention: `Test<Type>_<Method>`.
Let's call this test `TestTime_ UnmarshalJSON`.

2020-07-12 09:31 UTC, shal commented on time_test.go
> +	jsonString := []byte(`
Something happened here, could you please replace it to ```[]byte(`{"time": 1583000643}`)```.

2020-07-12 09:31 UTC, shal commented on time_test.go
> +	expectedData := Transaction{
I don't think, that test should actually now about `Transaction`, let's do simple `type struct{Time Time}` for testing.

2020-07-12 09:31 UTC, shal commented on time_test.go
> +func TestTime_JsonMarshal(t *testing.T) {
Let's call this test `TestTime_ MarshalJSON `.

2020-07-12 09:31 UTC, shal commented on personal_test.go
> +func TestPersonal_Transactions(t *testing.T) {
Unfortunately, we shouldn't put this changes into the PR. It is out of the scope. 
Our tests are pretty poor, let's keep these changes for PR for #29.

2020-07-12 09:31 UTC, shal commented on time_test.go
> +		t.Fatalf("expected error: nil, actual error: %v", err)
`t.Errorf` would be a better solution here.

2020-07-12 09:31 UTC, shal commented on time_test.go
> +	if expectedData != actualData {
There is a helper for that: `assertEqual`. Would you mind using it?

2020-07-26 08:44 UTC, SuddenGunter commented
@shal fixed

2020-07-27 07:37 UTC, shal approved these changes

2020-07-27 07:38 UTC, merged